version: '3'

services:

  card-players-unite-api:

    container_name: card-players-unite-api

    image: softwareshinobi/card-players-unite-api

    restart: unless-stopped

    ports:

      - "23089:8000"
                       
    networks:

        - network-card-players-unite-api
            
networks:

    network-card-players-unite-api:
    