# Dockerfile Fixing Stuff

## No module named 'django'

RUN set -xe \
     && pip install django
     
     
      
## install python3

RUN set -xe \
    && apt-get update \
    && apt-get install -y python3 \
    && apt-get install -y python3-pip

## install django api things

